import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://bluerosetech01.pegalabs.io/prweb/app/default/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD');
  await page.getByRole('textbox', { name: 'User name *' }).click();
  await page.getByRole('textbox', { name: 'User name *' }).click();
  await page.getByRole('textbox', { name: 'User name *' }).fill('csr_test');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('pega@12345');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId(':privacy-dialog:accept').click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByTestId(':menu-item:').click();
  await page.getByRole('button', { name: 'Fill form with AI' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('cell', { name: 'Premium Select' }).locator('div').nth(1).click();
  await page.getByRole('button', { name: 'Approve' }).click();
  await page.getByRole('tabpanel', { name: 'Self' }).getByTestId('Gender:select:control').selectOption('Male');
  await page.getByRole('tabpanel', { name: 'Self' }).getByTestId('Blood Group:select:control').selectOption('A+');
  await page.getByTestId('Marital Status:select:control').selectOption('Married');
  await page.getByTestId('Nationality:input:control').click();
  await page.getByTestId('Nationality:input:control').fill('American');
  await page.getByRole('tab', { name: 'Partner' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Monica');
  await page.getByRole('spinbutton', { name: 'day' }).click();
  await page.getByRole('tab', { name: 'Self' }).click();
  await page.getByRole('tab', { name: 'Partner' }).click();
  await page.getByRole('spinbutton', { name: 'day' }).click();
  await page.getByRole('spinbutton', { name: 'day' }).fill('01');
  await page.getByRole('spinbutton', { name: 'month' }).fill('01');
  await page.getByRole('spinbutton', { name: 'year' }).fill('1985');
  await page.getByRole('spinbutton', { name: 'year' }).press('Tab');
  await page.getByRole('application').locator('div').click();
  await page.getByRole('textbox', { name: 'Age.' }).fill('40');
  await page.getByTestId('Relationship:input:control').click();
  await page.getByTestId('Relationship:input:control').fill('Spouse');
  await page.getByTestId('Relationship:input:control').press('Tab');
  await page.getByRole('tabpanel', { name: 'Partner' }).getByTestId('Gender:select:control').selectOption('Female');
  await page.getByRole('tabpanel', { name: 'Partner' }).getByTestId('Blood Group:select:control').selectOption('AB+');
  await page.getByRole('tab', { name: 'Child' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Alex');
  await page.getByRole('spinbutton', { name: 'day' }).click();
  await page.getByRole('spinbutton', { name: 'day' }).click();
  await page.getByRole('spinbutton', { name: 'day' }).dblclick();
  await page.getByRole('spinbutton', { name: 'day' }).click();
  await page.getByRole('spinbutton', { name: 'day' }).fill('01');
  await page.getByRole('spinbutton', { name: 'month' }).fill('01');
  await page.getByRole('spinbutton', { name: 'year' }).fill('2020');
  await page.getByRole('textbox', { name: 'Age.' }).click();
  await page.getByRole('textbox', { name: 'Age.' }).fill('5');
  await page.getByRole('group', { name: 'Child' }).getByTestId('Gender:select:control').selectOption('Male');
  await page.getByRole('group', { name: 'Child' }).getByTestId('Blood Group:select:control').selectOption('AB+');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('banner').getByRole('button', { name: 'csr test' }).click();
  await page.getByText('Log off').click();
});